### ISSUE TITLE
Ulauncher v5.6.1 - extension doesn't get installed

### ISSUE THREAD

**Issue by rkmaier** [beajeanm/ulauncher-windows-switcher#4]
When adding the extension using the github link in Ulauncher nothing happens

**Comment by raduone** [comment]
Any update on this ?
Is there any workaround ?

**Comment by leobragatti** [comment]
@raduone, try using this repository:
https://github.com/rabin-io/ulauncher-windows-switcher

The guy already submitted a pull request, but you have to wait the owner to merge it

**Comment by raduone** [comment]
@leobragatti Thank you !
