### ISSUE TITLE
Doesn't work for me under Xubuntu Bionic

### ISSUE THREAD

**Issue by zz0rk** [beajeanm/ulauncher-windows-switcher#5]
When I type 'ws + space' I get a search icon plus the text  'Loading...' but no windows are being listed. Using ulauncher_5.7.3_all.deb

libwnck-3-0
3.24.1-2

libwnck-3-common
3.24.1-2

**Comment by DraggonFantasy** [comment]
Same under Ubuntu 16.04

Ulauncher 5.7.5
libwnck-3-0 : 3.14.1-2
