### ISSUE TITLE
does not add extension in Ubuntu 20.04

### ISSUE THREAD

**Issue by mpetit987** [beajeanm/ulauncher-windows-switcher#6]
Ubuntu 20.04 + Ulauncher 5.8.0 + Extension API v2.0.0

Add extension https://github.com/beajeanm/ulauncher-windows-switcher

then click on Add button does nothing!

It does not add the extension!

**Comment by mad-ady** [comment]
It complains about this:
```
2020-09-29 13:04:11,159 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Could not find versions.json file using URL "https://raw.githubusercontent.com/beajeanm/ulauncher-windows-switcher/master/versions.json
```

**Comment by mad-ady** [comment]
Switched to this fork - which works fine: https://github.com/merrickluo/ulauncher-windows-switcher

**Comment by mpetit987** [comment]
Thanks mad-ady, I validate it is working now on Ubuntu 20.04.

**Comment by mpetit987** [comment]
Now this should be updated: [https://ext.ulauncher.io/](url)

**Comment by antonycms** [comment]
the only one that works for me is https://github.com/psukys/ulauncher-plugin-windows, but unfortunately it does not display application icons.
